# Generated by Django 5.2.1 on 2025-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoBiseccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=100)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('tolerancia', models.FloatField(default=0.0001)),
                ('resultado', models.TextField()),
            ],
        ),
    ]
